name: ble_peripheral
description: Ble peripheral is a Flutter plugin that allows you to use your device as Bluetooth Low Energy (BLE) peripheral
version: 2.3.2
homepage: https://github.com/rohitsangwan01/ble_peripheral
repository: https://github.com/rohitsangwan01/ble_peripheral
issue_tracker: https://github.com/rohitsangwan01/ble_peripheral/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^17.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rohit.ble_peripheral
        pluginClass: BlePeripheralPlugin
      ios:
        pluginClass: BlePeripheralPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: BlePeripheralPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: BlePeripheralPluginCApi
