name: ble_peripheral
description: Ble peripheral is a Flutter plugin that allows you to use your device as Bluetooth Low Energy (BLE) peripheral
version: 0.0.1
homepage: https://github.com/rohitsangwan01/ble_peripheral
repository: https://github.com/rohitsangwan01/ble_peripheral
issue_tracker: https://github.com/rohitsangwan01/ble_peripheral/issues

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  pigeon: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rohit.ble_peripheral
        pluginClass: BlePeripheralPlugin
      ios:
        pluginClass: BlePeripheralPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: BlePeripheralPlugin
        sharedDarwinSource: true
      linux:
        pluginClass: BlePeripheralPlugin  
      windows:
        pluginClass: BlePeripheralPluginCApi
  